## LAB 5.1 REDES NEURONALES

**Probando si pytorch se instalo correctamente**

In [33]:
import torch

# Verifica si PyTorch detecta la GPU
print(f"¿CUDA disponible?: {torch.cuda.is_available()}")

# Muestra el nombre de tu GPU (ej. Acer Predator / GTX / RTX)
if torch.cuda.is_available():
    print(f"GPU detectada: {torch.cuda.get_device_name(0)}")
    print(f"Versión de CUDA de PyTorch: {torch.version.cuda}")

¿CUDA disponible?: True
GPU detectada: GeForce RTX 2070 with Max-Q Design
Versión de CUDA de PyTorch: 11.0


In [34]:
x = torch.randn(5, 3, 2)
x

tensor([[[-6.8883e-01,  8.4547e-01],
         [-1.9245e+00,  5.4686e-02],
         [-1.1429e+00,  1.9181e-01]],

        [[-3.6222e-01,  1.8676e-01],
         [-1.2869e+00, -1.0943e+00],
         [-1.8149e-03, -8.9000e-01]],

        [[ 8.3531e-01,  1.7738e+00],
         [ 4.7830e-01, -1.1391e+00],
         [-3.8052e-01,  1.0339e+00]],

        [[-6.8692e-01, -6.1785e-01],
         [ 1.6774e+00,  1.0320e+00],
         [ 8.6466e-01,  6.6475e-01]],

        [[-1.4812e-01, -2.2159e-01],
         [-1.9103e-01, -4.0217e-01],
         [-3.8201e-01,  1.3690e+00]]])

In [35]:
x[0][0][1]

tensor(0.8455)

In [36]:
x.shape


torch.Size([5, 3, 2])

In [37]:
m = torch.randn(3,3)
m

tensor([[-0.9108, -0.7917, -0.8045],
        [ 1.8524, -0.3912,  1.1542],
        [ 1.2713, -0.0948,  1.0827]])

In [38]:
m.view(1,3,3).shape

torch.Size([1, 3, 3])

In [39]:
m

tensor([[-0.9108, -0.7917, -0.8045],
        [ 1.8524, -0.3912,  1.1542],
        [ 1.2713, -0.0948,  1.0827]])

In [40]:
a = m.view(1,9)
a

tensor([[-0.9108, -0.7917, -0.8045,  1.8524, -0.3912,  1.1542,  1.2713, -0.0948,
          1.0827]])

In [41]:
x = torch.randn(10000,1000).cuda()
y = torch.randn(10000,1000).cuda()

%time z = x*y

CPU times: total: 0 ns
Wall time: 17 ms
